Setting.save_default(:full_name,'GetViable')
Setting.save_default(:header_logo,'getviable.png')
Setting.save_default(:facebook,'')
Setting.save_default(:twitter,'')
Setting.save_default(:googleplus,'')
Setting.save_default(:linkedin,'')
Setting.save_default(:social_login, ENV['GETVIABLE_SOCIAL_LOGINS'] || 'true')
Setting.save_default(:groups_enabled, ENV['GETVIABLE_GROUP_FUNCTIONALITY'] || 'false')
Setting.save_default(:optimizely,'')
Setting.save_default(:payments_enabled,'true')